ERROR - 2023-03-15 21:24:58 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'repaso', 3306, '', 0)
#1 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Proyecto\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Proyecto\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Proyecto\app\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(934): App\Controllers\productoController->index()
#8 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
#9 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Proyecto\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Proyecto\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Proyecto\app\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(934): App\Controllers\productoController->index()
#7 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
#8 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-15 21:24:58 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `productos`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\productoController->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-15 21:27:02 --> Class 'objet' not found
in SYSTEMPATH\Database\MySQLi\Result.php on line 152.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-03-15 21:28:38 --> Undefined variable: productos
in APPPATH\Views\index.php on line 2.
 1 APPPATH\Views\index.php(2): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: productos', 'APPPATH\\Views\\index.php', 2, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('index', [], true)
 5 APPPATH\Controllers\productoController.php(13): view('index', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\productoController->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-15 21:50:19 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'celayacvtf13', 'repaso', 3306, '', 0)
#1 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Proyecto\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Proyecto\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Proyecto\app\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(934): App\Controllers\productoController->index()
#8 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
#9 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Proyecto\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Proyecto\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Proyecto\app\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(934): App\Controllers\productoController->index()
#7 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
#8 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-15 21:50:19 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `productos`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\productoController->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-15 21:52:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', 'celayacvtf13', 'repaso', 3306, '', 0)
#1 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Proyecto\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Proyecto\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Proyecto\app\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(934): App\Controllers\productoController->index()
#8 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
#9 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Proyecto\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Proyecto\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Proyecto\app\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(934): App\Controllers\productoController->index()
#7 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
#8 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-15 21:52:34 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `productos`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\productoController->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-15 21:53:09 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'repaso' in C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'repaso', 3306, '', 0)
#1 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Proyecto\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Proyecto\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Proyecto\app\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(934): App\Controllers\productoController->index()
#8 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
#9 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'repaso' in C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Proyecto\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Proyecto\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Proyecto\app\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(934): App\Controllers\productoController->index()
#7 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
#8 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-15 21:53:09 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'repaso'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `productos`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\productoController->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-15 21:54:06 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'repaso' in C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'repaso', 3306, '', 0)
#1 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Proyecto\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Proyecto\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Proyecto\app\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(934): App\Controllers\productoController->index()
#8 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
#9 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'repaso' in C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Proyecto\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Proyecto\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Proyecto\app\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(934): App\Controllers\productoController->index()
#7 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
#8 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-15 21:54:06 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'repaso'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `productos`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\productoController->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-15 21:58:05 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'repaso' in C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'repaso', 3306, '', 0)
#1 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Proyecto\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Proyecto\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Proyecto\app\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(934): App\Controllers\productoController->index()
#8 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
#9 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'repaso' in C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Proyecto\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Proyecto\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Proyecto\app\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(934): App\Controllers\productoController->index()
#7 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
#8 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-15 21:58:05 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'repaso'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `productos`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\productoController->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-15 22:05:51 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'repaso' in C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'repaso', 3306, '', 0)
#1 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Proyecto\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Proyecto\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Proyecto\app\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(934): App\Controllers\productoController->index()
#8 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
#9 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'repaso' in C:\xampp\htdocs\Proyecto\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Proyecto\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Proyecto\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Proyecto\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Proyecto\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Proyecto\app\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(934): App\Controllers\productoController->index()
#7 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
#8 C:\xampp\htdocs\Proyecto\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Proyecto\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-15 22:05:51 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'repaso'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `productos`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\productoController.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\productoController->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-15 22:08:12 --> Undefined variable: productos
in APPPATH\Views\index.php on line 22.
 1 APPPATH\Views\index.php(22): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: productos', 'APPPATH\\Views\\index.php', 22, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('index', [], true)
 5 APPPATH\Controllers\productoController.php(13): view('index', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\productoController->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-15 22:12:38 --> Undefined property: stdClass::$eistencias
in APPPATH\Views\index.php on line 26.
 1 APPPATH\Views\index.php(26): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined property: stdClass::$eistencias', 'APPPATH\\Views\\index.php', 26, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('index', [], true)
 5 APPPATH\Controllers\productoController.php(13): view('index', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\productoController->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-15 22:41:31 --> syntax error, unexpected '{', expecting variable (T_VARIABLE)
in APPPATH\Controllers\productoController.php on line 23.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\productoController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\productoController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\productoController')
 4 [internal function]: spl_autoload_call('App\\Controllers\\productoController')
 5 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\productoController', true)
 6 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-15 22:46:54 --> syntax error, unexpected 'marcas' (T_STRING), expecting ')'
in APPPATH\Controllers\productoController.php on line 26.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\productoController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\productoController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\productoController')
 4 [internal function]: spl_autoload_call('App\\Controllers\\productoController')
 5 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\productoController', true)
 6 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-15 23:28:26 --> syntax error, unexpected '/'
in APPPATH\Views\plantilla.php on line 9.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->render('plantilla', [], true)
 3 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('index', [], true)
 4 APPPATH\Controllers\productoController.php(21): view('index', [...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\productoController->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-15 23:36:41 --> syntax error, unexpected '/'
in APPPATH\Views\plantilla.php on line 9.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->render('plantilla', [], true)
 3 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('index', [], true)
 4 APPPATH\Controllers\productoController.php(21): view('index', [...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\productoController->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-15 23:54:21 --> syntax error, unexpected '/'
in APPPATH\Views\plantilla.php on line 9.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->render('plantilla', [], true)
 3 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('index', [], true)
 4 APPPATH\Controllers\productoController.php(21): view('index', [...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\productoController->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\productoController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
